Refactor CI workflows

diff --git a/.github/workflows/collector-test.yaml b/.github/workflows/collector-test.yaml
--- a/.github/workflows/collector-test.yaml
+++ b/.github/workflows/collector-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  collector-test:
+  collector-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -37,3 +37,17 @@ jobs:
           kubectl apply -f ./charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered
           kubectl rollout status daemonset example-opentelemetry-collector-agent --timeout=30s
           kubectl rollout status deployment example-opentelemetry-collector --timeout=30s
+
+  collector-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [collector-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.collector-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/demo-test.yaml b/.github/workflows/demo-test.yaml
--- a/.github/workflows/demo-test.yaml
+++ b/.github/workflows/demo-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  demo-test:
+  demo-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -36,3 +36,17 @@ jobs:
           --chart-repos grafana=https://grafana-community.github.io/helm-charts
           --chart-repos jaeger=https://jaegertracing.github.io/helm-charts
           --chart-repos opensearch=https://opensearch-project.github.io/helm-charts"
+
+  demo-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [demo-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.demo-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/ebpf-test.yaml b/.github/workflows/ebpf-test.yaml
--- a/.github/workflows/ebpf-test.yaml
+++ b/.github/workflows/ebpf-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  ebpf-test:
+  ebpf-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -44,3 +44,17 @@ jobs:
           kubectl rollout status deployment example-opentelemetry-ebpf-cloud-collector --timeout=30s
           kubectl rollout status deployment example-opentelemetry-ebpf-k8s-collector --timeout=30s
           kubectl rollout status deployment example-opentelemetry-ebpf-reducer --timeout=30s
+
+  ebpf-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [ebpf-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.ebpf-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/kube-stack-test.yaml b/.github/workflows/kube-stack-test.yaml
--- a/.github/workflows/kube-stack-test.yaml
+++ b/.github/workflows/kube-stack-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  opentelemetry-kube-stack-test:
+  kube-stack-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -40,3 +40,17 @@ jobs:
         run: |
           helm dep build charts/opentelemetry-kube-stack
           helm install opentelemetry-kube-stack charts/opentelemetry-kube-stack
+
+  opentelemetry-kube-stack-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [kube-stack-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.kube-stack-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -9,7 +9,7 @@ permissions:
   contents: read
 
 jobs:
-  lint-test:
+  lint-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -37,3 +37,17 @@ jobs:
 
       - name: Run make check-examples
         run: make check-examples
+
+  lint-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [lint-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.lint-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/operator-test.yaml b/.github/workflows/operator-test.yaml
--- a/.github/workflows/operator-test.yaml
+++ b/.github/workflows/operator-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  operator-test:
+  operator-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -83,7 +83,21 @@ jobs:
           mkdir -p ./.testresults/e2e
           chainsaw test --test-dir ./tests/e2e --exclude-test-regex "chainsaw/multiple-configmaps" --exclude-test-regex "chainsaw/smoke-pod-dns-config" --exclude-test-regex "chainsaw/operator-metrics"
 
-  operator-test-no-certmanager:
+  operator-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [operator-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.operator-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
+
+  operator-test-no-certmanager-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -149,3 +163,17 @@ jobs:
         run: |
           mkdir -p ./.testresults/e2e
           chainsaw test --test-dir ./tests/e2e --exclude-test-regex "chainsaw/multiple-configmaps" --exclude-test-regex "chainsaw/smoke-pod-dns-config" --exclude-test-regex "chainsaw/operator-metrics"
+
+  operator-test-no-certmanager:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [operator-test-no-certmanager-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.operator-test-no-certmanager-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
diff --git a/.github/workflows/ta-test.yaml b/.github/workflows/ta-test.yaml
--- a/.github/workflows/ta-test.yaml
+++ b/.github/workflows/ta-test.yaml
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  ta-test:
+  ta-test-matrix:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -36,3 +36,17 @@ jobs:
         run: |
           kubectl apply -f ./charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered
           kubectl rollout status deployment example-opentelemetry-target-allocator-ta --timeout=30s
+
+  ta-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [ta-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.ta-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
