ci: Add CI support for Helm v4 (#2215)
* ci: Add CI support for Helm v4

* Address review: keeping old Helm v3 versions

Signed-off-by: vanshiz <vanshikabhargava29@gmail.com>

* Refactor CI workflows

---------

Signed-off-by: vanshiz <vanshikabhargava29@gmail.com>
Co-authored-by: Tyler Helmuth <12352919+TylerHelmuth@users.noreply.github.com>

diff --git a/.github/workflows/collector-test.yaml b/.github/workflows/collector-test.yaml
--- a/.github/workflows/collector-test.yaml
+++ b/.github/workflows/collector-test.yaml
@@ -11,8 +11,13 @@ permissions:
   contents: read
 
 jobs:
-  collector-test:
+  collector-test-matrix:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        helm-version:
+          - "v3.9.4"
+          - "v4.0.3"
     steps:
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -22,6 +27,7 @@ jobs:
         uses: ./.github/actions/setup
         with:
           create-kind-cluster: "true"
+          helm-version: ${{ matrix.helm-version }}
 
       - name: Run chart-testing (install)
         run: ct install --charts charts/opentelemetry-collector
@@ -31,3 +37,17 @@ jobs:
           kubectl apply -f ./charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered
           kubectl rollout status daemonset example-opentelemetry-collector-agent --timeout=30s
           kubectl rollout status deployment example-opentelemetry-collector --timeout=30s
+
+  collector-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [collector-test-matrix]
+    steps:
+      - name: Check matrix result
+        run: |
+          if [[ "${{ needs.collector-test-matrix.result }}" == "success" ]]; then
+            echo "All matrix jobs passed!"
+          else
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
