added error code

diff --git a/.github/workflows/lint-test.yaml b/.github/workflows/lint-test.yaml
--- a/.github/workflows/lint-test.yaml
+++ b/.github/workflows/lint-test.yaml
@@ -47,7 +47,8 @@ jobs:
             if diff "${d}/manifest" "./test/${d}/opentelemetry-collector/templates" >/dev/null; then
                 echo "Passed ${d}";
             else
-                echo "Failed ${d}";
+                echo "Failed ${d}. Check that manifest/ has been rendered with the latest ${d}/values.yaml";
+                exit 1                
             fi
           done
 
